In [1]:
import pandas as pd
import numpy as np

In [3]:
months = ["1901", "1902", "1903", "1904", "1905", "1906", "2001", "2002", "2003", "2004", "2005", "2006"]
main_df = pd.DataFrame()

for month in months:
    print(month)
    filepath = f"Data/data/20{month}-citibike-tripdata.csv"
    df = pd.read_csv(filepath, low_memory=False)
    df = df.sample(frac=0.015, random_state=42)
    main_df = main_df.append(df)
    
main_df = main_df.reset_index(drop=True)

1901
1902
1903
1904
1905
1906
2001
2002
2003
2004
2005
2006

In [4]:
main_df.to_csv("19Q1vs20Q1_citibike_rides_sample.csv", index=False)

In [5]:
main_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,574,2019-01-30 17:30:59.7870,2019-01-30 17:40:34.2530,359.0,E 47 St & Park Ave,40.755103,-73.974987,528.0,2 Ave & E 31 St,40.742909,-73.977061,33216,Subscriber,1993,1
1,709,2019-01-23 19:28:12.1530,2019-01-23 19:40:01.7030,493.0,W 45 St & 6 Ave,40.756800,-73.982912,3159.0,W 67 St & Broadway,40.774925,-73.982666,16092,Subscriber,1990,1
2,1993,2019-01-26 18:30:29.2160,2019-01-26 19:03:43.0780,503.0,E 20 St & Park Ave,40.738274,-73.987520,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,34868,Subscriber,1977,1
3,392,2019-01-05 18:31:40.6190,2019-01-05 18:38:13.1980,161.0,LaGuardia Pl & W 3 St,40.729170,-73.998102,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,31405,Subscriber,1996,1
4,543,2019-01-23 15:24:24.9240,2019-01-23 15:33:28.8630,3496.0,1 Ave & E 110 St,40.792327,-73.938300,3671.0,E 81 St & 2 Ave,40.774779,-73.954275,35695,Subscriber,1998,1

In [6]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248455 entries, 0 to 248454
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tripduration             248455 non-null  int64
 1   starttime                248455 non-null  object
 2   stoptime                 248455 non-null  object
 3   start station id         248455 non-null  float64
 4   start station name       248455 non-null  object
 5   start station latitude   248455 non-null  float64
 6   start station longitude  248455 non-null  float64
 7   end station id           248455 non-null  float64
 8   end station name         248455 non-null  object
 9   end station latitude     248455 non-null  float64
 10  end station longitude    248455 non-null  float64
 11  bikeid                   248455 non-null  int64
 12  usertype                 248455 non-null  object
 13  birth year               248455 non-null  int64
 14  gender                   248455 non-null  int64
dtypes: float64(6), int64(4), object(5)
memory usage: 28.4+ MB